server:
  port: 8085

spring:
  application:
    name: progress-tracking-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tracking_db
    username: tracking_user
    password: tracking_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: your-secret-key-change-in-production

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    edu.unicauca.progress: DEBUG

