server:
  port: 8082

spring:
  application:
    name: submission-service

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:submission-postgres}:${DATABASE_PORT:5432}/${DATABASE_NAME:submissiondb}
    username: ${DATABASE_USERNAME:submission_user}
    password: ${DATABASE_PASSWORD:submission_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # validate en producción
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin_password}

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB

# Almacenamiento de archivos
file:
  storage:
    path: ${FILE_STORAGE_PATH:/app/uploads}

# Configuración de RabbitMQ - Exchanges y Routing Keys
submission:
  exchanges:
    formato-a: formato-a-exchange
    anteproyecto: anteproyecto-exchange
    proyecto: proyecto-exchange
  routing:
    formato-a-enviado: formato-a.enviado
    formato-a-reenviado: formato-a.reenviado
    anteproyecto-enviado: anteproyecto.enviado
    proyecto-rechazo-def: proyecto.rechazado-definitivamente

# Cliente HTTP para Notification Service (opcional)
notification:
  base-url: ${NOTIFICATION_SERVICE_URL:http://notification-service:8083/api/notifications}
  timeout-ms: 3000

# Logging
logging:
  level:
    root: INFO
    co.unicauca.comunicacionmicroservicios: DEBUG
    org.springframework.amqp: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: true
    db:
      enabled: true
