version: '3.8'

# ============================================================
# DOCKER COMPOSE LOCAL - GATEWAY SERVICE
# ============================================================
# Este archivo va en: gateway-service/docker-compose.yml
# Solo para desarrollo/testing del gateway de forma aislada
# ============================================================

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service-local
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET=${JWT_SECRET}
      - GATEWAY_PORT=${GATEWAY_PORT:-8080}
      - GATEWAY_ENFORCE_ROLE_CHECK=${GATEWAY_ENFORCE_ROLE_CHECK:-false}
      - GATEWAY_CONNECT_TIMEOUT=${GATEWAY_CONNECT_TIMEOUT:-5000}
      - GATEWAY_READ_TIMEOUT=${GATEWAY_READ_TIMEOUT:-30000}
      # URLs apuntando a host.docker.internal para desarrollo local
      - IDENTITY_URL=http://host.docker.internal:8081
      - SUBMISSION_URL=http://host.docker.internal:8082
      - NOTIFICATION_URL=http://host.docker.internal:8083
      - REVIEW_URL=http://host.docker.internal:8084
      - TRACKING_URL=http://host.docker.internal:8085
      - RABBITMQ_HOST=${RABBITMQ_HOST:-host.docker.internal}
      - RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gateway-local-network

networks:
  gateway-local-network:
    driver: bridge

# NOTA: Este docker-compose es solo para desarrollo del gateway.
# Para ejecutar el sistema completo, usa el docker-compose.yaml de la raíz.